[build]
  base = "app"
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Force clean builds
  NETLIFY_SKIP_MANUAL_BUILD = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true